///<reference types = "Cypress" />

import { VehicleAction } from "../../../support/portal/actions/VehicleAction";


const vehicle = new VehicleAction

describe('Vehicle tab ',()=>{
    beforeEach(()=>{
        cy.visit('/')
        cy.login()
    })
    it('TC_VEHICLES_1 Add Vehicle by filling all sections (Basic Info, Advance Detail, Other Detail, Comments, Coast  Images, Custom) using Old vehicle data with Not arrived data',()=>{
        vehicle.validateDashboard()
        vehicle.createVehicle()
        let regNo = vehicle.generateRandomNumber(5)
        let VIN = vehicle.generateRandomNumber(4)
        vehicle.addBasicDetails(regNo, VIN)
        vehicle.advanceDetail()
        vehicle.addOtherDetails()
        vehicle.addCosts()
       // vehicle.addComments()
        vehicle.addImage()
        vehicle.addCustomDetail()
        vehicle.addVehicleButton()
        vehicle.verifySuccessToastMsg()
        vehicle.deleteVehicle(0)
        vehicle.verifySuccessToastMsg()
    })
    it('TC_VEHICLES_2  Add Vehicle without filling all sections (Basic Info, Advance Detail, Other Detail, Comments, Coast  Images, Custom) using Old vehicle data',()=>{
        vehicle.validateDashboard()
        vehicle.createVehicle()
        vehicle.addVehicleButton()
        vehicle.verifySuccessToastMsg()
        vehicle.deleteVehicle(0)
        vehicle.verifySuccessToastMsg()
    })
    it('TC_VEHICLES_3  Add Vehicle by filling all sections (Basic Info, Advance Detail, Other Detail, Comments, Coast  Images, Custom) using Old vehicle data by using AutoFill',()=>{
        vehicle.validateDashboard()
        vehicle.createVehicle()
        vehicle.autoFillBasicInfo()
        vehicle.addVehicleButton()
        vehicle.verifySuccessToastMsg()
        vehicle.deleteVehicle(0)
        vehicle.verifySuccessToastMsg()
    })
    it('TC_VEHICLES_4 Add Vehicle & Add Another after filling valid data in all sections (Basic Info, Advance Detail, Other Detail, Comments, Coast  Images, Custom) using Old vehicle data',()=>{
        vehicle.validateDashboard()
        vehicle.createVehicle()
        let regNo = vehicle.generateRandomNumber(5)
        let VIN = vehicle.generateRandomNumber(4)
        vehicle.addBasicDetails(regNo, VIN)
        vehicle.advanceDetail()
        vehicle.addOtherDetails()
        vehicle.addCosts()
       // vehicle.addComments()
        vehicle.addImage()
        vehicle.addCustomDetail()
        vehicle.addVehicleAndAddAnotherButton()
        vehicle.verifySuccessToastMsg()
        vehicle.searchTab()
        vehicle.removeArriveFilter()
        vehicle.applyOnlyShowVehiclesFilter()
        vehicle.searchInventory(VIN)
        vehicle.deleteVehicle(0)
        vehicle.verifySuccessToastMsg()
    })
    it('TC_VEHICLES_5  Add Vehicle & Add Another without filling all sections (Basic Info, Advance Detail, Other Detail, Comments, Coast  Images, Custom) using Old vehicle data',()=>{
        vehicle.validateDashboard()
        vehicle.createVehicle()
        vehicle.addVehicleAndAddAnotherButton()
        vehicle.verifySuccessToastMsg()
        vehicle.searchTab()
        vehicle.removeArriveFilter()
        vehicle.applyOnlyShowVehiclesFilter()
        vehicle.deleteVehicle(0)
        vehicle.verifySuccessToastMsg()
    })
    it(' TC_VEHICLES_6  Add Vehicle & Add Another without filling all sections (Basic Info, Advance Detail, Other Detail, Comments, Coast  Images, Custom) using Old vehicle data by using AutoFill',()=>{
        vehicle.validateDashboard()
        vehicle.createVehicle()
        vehicle.autoFillBasicInfo()
        vehicle.addVehicleAndAddAnotherButton()
        vehicle.verifySuccessToastMsg()
        vehicle.searchTab()
        vehicle.removeArriveFilter()
        vehicle.applyOnlyShowVehiclesFilter()
        vehicle.deleteVehicle(0)
        vehicle.verifySuccessToastMsg()
    })
    it('TC_VEHICLES_7 Add Vehicle & Print Tag after filling in valid data in all sections (Basic Info, Advance Detail, Other Detail, Comments, Coast  Images, Custom) using Old vehicle data',()=>{
        vehicle.validateDashboard()
        vehicle.createVehicle()
        let regNo = vehicle.generateRandomNumber(5)
        let VIN = vehicle.generateRandomNumber(4)
        vehicle.addBasicDetails(regNo, VIN)
        vehicle.advanceDetail()
        vehicle.addOtherDetails()
        vehicle.addCosts()
       // vehicle.addComments()
        vehicle.addImage()
        vehicle.addCustomDetail()
        vehicle.addVehicleAndPrintTagButton()
            })
    it(' TC_VEHICLES_8 Add Vehicle & Print Tag without filling all sections (Basic Info, Advance Detail, Other Detail, Comments, Coast  Images, Custom) using Old vehicle data',()=>{
        vehicle.validateDashboard()
        vehicle.createVehicle()
        vehicle.addVehicleAndPrintTagButton()

    })
    it(' TC_VEHICLES_9 Add Vehicle & Print Tag after filling in valid data in all sections (Basic Info, Advance Detail, Other Detail, Comments, Coast  Images, Custom) using Old vehicle data by Auto Fill',()=>{
        vehicle.validateDashboard()
        vehicle.createVehicle()
        vehicle.autoFillBasicInfo()
        vehicle.addVehicleAndPrintTagButton()
    })
    it(' TC_VEHICLES_10 Validate the Cancel option on Add Vehicle',()=>{
        vehicle.validateDashboard()
        vehicle.createVehicle()
        vehicle.autoFillBasicInfo()
        vehicle.cancelButton()
    })
})


