///<reference types = "Cypress"/>

import { InvoiceAction } from "../../../support/portal/actions/InvoiceAction"


const invoice = new InvoiceAction

describe('Add Invoice', () => {
  beforeEach(() => {
    cy.login()
    
  })
  it('TC-1 Add Invoice Successfully', () => {
    invoice.createInvoice()
    invoice.addInvoiceDetails()
    invoice.addRow('addShipping')
    invoice.setDescription(0, 'Shipping')
    invoice.setQuantity(0, '1')
    invoice.setPrice(0, '100')
    invoice.setAccount(0, 'Zero Rated')
    invoice.setTax(0, 'Zero Rated')
    invoice.saveCloseButton()
    invoice.verifySuccess()
    invoice.deleteInvoice()
    invoice.verifySuccess()

  })
  it('TC-2 Add Invoice with Multiple Line Items', () => {
    invoice.createInvoice()
    invoice.addInvoiceDetails()
    invoice.addRow('addLabour')
    invoice.setDescription(0, 'Car parts')
    invoice.setQuantity(0, '1')
    invoice.setPrice(0, '100')
    invoice.setAccount(0, 'Zero Rated')
    invoice.setTax(0, 'Zero Rated')
    //add 2nd row 
    invoice.addRow('addShipping')
    invoice.setDescription(1, 'Shipping')
    invoice.setQuantity(1, '1')
    invoice.setPrice(1, '100')
    invoice.setAccount(1, '15% GST on Income')
    invoice.saveCloseButton()
    invoice.verifySuccess()
    invoice.deleteInvoice()
    invoice.verifySuccess()
  })
  it('TC-3A Add Invoice Successfully with Approve & Email Approve', () => {
    //Approved $Email
    invoice.createInvoice()
    invoice.addInvoiceDetails()
    invoice.addRow('addLabour')
    invoice.setDescription(0, 'Labour')
    invoice.setQuantity(0, '1')
    invoice.setPrice(0, '100')
    invoice.setAccount(0, 'Zero Rated')
    invoice.setTax(0, 'Zero Rated')
    //add 2nd row 
    invoice.addRow('addShipping')
    invoice.setDescription(1, 'Shipping')
    invoice.setQuantity(1, '1')
    invoice.setPrice(1, '100')
    invoice.setAccount(1, '15% GST on Income')
    invoice.approveEmailButton()
    invoice.verifySuccess()
    //cannot delete which is approved by email 

  })
  it('TC-3B Add Invoice Successfully with Approved and add another', () => {
    //Approved and add another
    invoice.createInvoice()
    invoice.addInvoiceDetails()
    invoice.addRow('addLabour')
    invoice.setDescription(0, 'Labour')
    invoice.setQuantity(0, '1')
    invoice.setPrice(0, '100')
    invoice.setAccount(0, 'Zero Rated')
    invoice.setTax(0, 'Zero Rated')
    //add 2nd row 
    invoice.addRow('addShipping')
    invoice.setDescription(1, 'Shipping')
    invoice.setQuantity(1, '1')
    invoice.setPrice(1, '100')
    invoice.setAccount(1, '15% GST on Income')
    invoice.approveAddanotherButton()
    invoice.verifySuccess()
  })
  it('TC-3C Add Invoice Successfully with Approved and print', () => {
    //Approved and print 
    invoice.createInvoice()
    invoice.addInvoiceDetails()
    invoice.addRow('addLabour')
    invoice.setDescription(0, 'Labour')
    invoice.setQuantity(0, '1')
    invoice.setPrice(0, '100')
    invoice.setAccount(0, 'Zero Rated')
    invoice.setTax(0, 'Zero Rated')
    //add 2nd row 
    invoice.addRow('addShipping')
    invoice.setDescription(1, 'Shipping')
    invoice.setQuantity(1, '1')
    invoice.setPrice(1, '100')
    invoice.setAccount(1, '15% GST on Income')
    invoice.approvePrintButton()
    invoice.verifySuccess()

  })
  it('TC-4 Add Invoice with Tax Calculation', () => {
    invoice.createInvoice()
    invoice.addInvoiceDetails()
    invoice.addRow('addLabour')
    invoice.setDescription(0, 'Labour')
    invoice.setQuantity(0, '1')
    invoice.setPrice(0, '100')
    invoice.setAccount(0, 'Zero Rated')
    invoice.setTax(0, 'Zero Rated')
    invoice.getAmount().then((amount) => {
    invoice.compareTax(amount, 0); //row amount and rate
    });
    invoice.saveCloseButton()
    invoice.verifySuccess()
    cy.wait(3000)
    invoice.deleteInvoice()
    invoice.verifySuccess()
    cy.wait(3000)
  })
  it('TC-5 Add Invoice - Change Quantity, Price, Amount, Tax Rate and Tax', () => {
    invoice.createInvoice()
    invoice.addInvoiceDetails()
    invoice.addRow('addLabour')
    invoice.setDescription(0, 'Labour')
    invoice.setQuantity(0, '2')
    invoice.setPrice(0, '100')
    invoice.setAccount(0, 'Zero Rated')
    invoice.setTax(0, 'Zero Rated')
    const previousPrice = invoice.getPrice()
    const previousQuantity = invoice.getQuantity()
    const previousAmount = invoice.getAmount()
    invoice.saveCloseButton()
    cy.wait(3000)
    invoice.verifySuccess()
    cy.wait(5000)
    invoice.goInvoicePage()
    invoice.viewInvoice(0)
    invoice.editInvoice()
    invoice.setQuantity(0, '3')
    invoice.setPrice(0, '200')
    const afterPrice = invoice.getPrice()
    const afterQuantity = invoice.getQuantity()
    const afterAmount = invoice.getAmount()
    invoice.clickSaveChanges()
    cy.wait(3000)
    invoice.verifySuccess()
    
    expect(afterPrice).to.be.not.eq(previousPrice)
    expect(afterQuantity).to.be.not.eq(previousQuantity)
    expect(afterAmount).to.be.not.eq(previousAmount)
    invoice.deleteInvoice()
    invoice.verifySuccess()
    cy.wait(3000)
  })
  it('TC-5-B  Add Invoice with Missing Information', () => {
    invoice.createInvoice()
    invoice.saveCloseButton()
    invoice.addInvoiceEmptyfields()
    invoice.saveCloseButton()
    invoice.verifyError()
  })
  it('TC-6 Verify error on adding Invalid invoice Item', () => {
    invoice.createInvoice()
    invoice.addInvoiceDetails()
    invoice.addRowWithInvalidata()
    invoice.verifyError()
    // On adding a invoice items all row fields are disabled
   //'Invoice must have atlease one part')
  })
  it('TC-7 Verify Tax Rate with Account', () => {
    invoice.createInvoice()
    invoice.addInvoiceDetails()
    invoice.addRow('addShipping')
    invoice.setDescription(0, 'Shipping')
    invoice.setQuantity(0, '1')
    invoice.setPrice(0, '100')
    invoice.setAccount(0, 'Zero Rated')
    invoice.setTax(0, '15% GST on Income') //tax rate is different from account type
    invoice.saveCloseButton()
    invoice.verifyError()
    
  })
  it('TC-8 Verify line Item with one field present (like Quantity)', () => {
    invoice.createInvoice()
    invoice.addInvoiceDetails()
    invoice.addRow('addOtherItem')
    invoice.setDescription(0, ' ') //blank
    invoice.setQuantity(0, '1') //only quantity
    invoice.setPrice(0, ' ')  //blank
    invoice.setAccount(0, 'Zero Rated')
    invoice.setTax(0, 'Zero Rated')
    invoice.saveCloseButton()
    invoice.verifyError()

  })
  it('TC- 9 Verify line Item with only description present', () => {
    invoice.createInvoice()
    invoice.addInvoiceDetails()
    invoice.addRow('addOtherItem')
    invoice.setDescription(0, 'Car parts')
    invoice.setQuantity(0, ' ') //Blank
    invoice.setPrice(0, '100')    //Blank
    invoice.setAccount(0, 'Zero Rated')
    invoice.setTax(0, 'Zero Rated')
    invoice.saveCloseButton()
    invoice.verifyError()
  })
  it('TC-10 Delete Line Items', () => {
    invoice.createInvoice()
    invoice.addRow('addShipping')
    invoice.addRow('addOtherItem')
    cy.wait(1000)
    invoice.deleteRow(0)
    invoice.deleteRow(0)
  })
  it('TC-11 Cancel Add Invoice', () => {
    invoice.createInvoice()
    invoice.cancelInvoice()

  })
  it('TC-12 Preview Add Invoice', () => {
    invoice.createInvoice()
    invoice.previewInvoice()

  })
  it('TC-13 Edit Previously Created Invoice Successfully', () => {
    invoice.goInvoicePage()
    invoice.viewInvoice(0)
    invoice.editInvoice() //Edit FIrst booking
    invoice.setQuantity(0, '3') //Change the quantity
    invoice.setPrice(0, '200')  //Change the price
    invoice.clickSaveChanges()
    invoice.verifySuccess()
  })
  it('TC-14 Edit the Previously Created Invoice and add new Line Items save it', () => {
    invoice.createInvoice()
    invoice.addInvoiceDetails()
    invoice.addRow('addShipping')
    invoice.setDescription(0, 'Shipping')
    invoice.setQuantity(0, '1')
    invoice.setPrice(0, '100')
    invoice.setAccount(0, 'Zero Rated')
    invoice.setTax(0, 'Zero Rated')
    invoice.saveCloseButton()
    invoice.verifySuccess()
    invoice.goInvoicePage()
    invoice.viewInvoice(0)
    invoice.editInvoice() //Edit FIrst booking
    //Add a new row item
    invoice.addRow('addShipping')
    invoice.setDescription(1, 'Shipping')
    invoice.setQuantity(1, '1')
    invoice.setPrice(1, '100')
    invoice.setAccount(1, '15% GST on Income')
    invoice.clickSaveChanges()
    invoice.verifySuccess()
    invoice.deleteInvoice()
    invoice.verifySuccess()
  })
  it('TC-15 Edit the Previously Created Invoice with Save & Print, Save & Print Packing Slip', () => {
    invoice.goInvoicePage()
    invoice.viewInvoice(0)
    invoice.editInvoice()
    invoice.savePrint()
    cy.wait(5000);
  })
  it('TC_16 Edit the Previously Created Invoice with Tax Calculation',()=>{
    invoice.createInvoice()
    invoice.addInvoiceDetails()
    invoice.addRow('addShipping')
    invoice.setDescription(0, 'Shipping')
    invoice.setQuantity(0, '1')
    invoice.setPrice(0, '100')
    invoice.setAccount(0, '15% GST on Income')
    invoice.setTax(0, '15% GST on Income')
    invoice.saveCloseButton()
    cy.wait(3000)
    invoice.goInvoicePage()
    invoice.viewInvoice(0)
    invoice.editInvoice()
    invoice.getPrice().then(price=>{
      invoice.compareTax(price,0.15)
    })
    invoice.clickSaveChanges()
    invoice.deleteInvoice()
  })
  it('TC-17 Edit the Previously Created Invoice and Change Quantity, Price, Amount',()=>{
    invoice.createInvoice()
    invoice.addInvoiceDetails()
    invoice.addRow('addShipping')
    invoice.setDescription(0, 'Shipping')
    invoice.setQuantity(0, '1')
    invoice.setPrice(0, '100')
    invoice.setAccount(0, '15% GST on Income')
    invoice.setTax(0, '15% GST on Income')
    const previousPrice = invoice.getPrice()
    const previousQuantity = invoice.getQuantity()
    const previousAmount = invoice.getAmount()
    invoice.saveCloseButton()
    invoice.verifySuccess()
    cy.wait(3000)
    cy.reload()
    invoice.goInvoicePage()
    invoice.viewInvoice(0)
    invoice.editInvoice()
    invoice.setQuantity(0, '2')
    invoice.setPrice(0, '200')
    invoice.setAccount(0, 'ACCRECPAY')
    const afterPrice = invoice.getPrice()
    const afterQuantity = invoice.getQuantity()
    const afterAmount = invoice.getAmount()
    cy.wait(5000)
    invoice.clickSaveChanges()
    invoice.verifySuccess()
    cy.reload()
    expect(afterPrice).to.be.not.eq(previousPrice)
    expect(afterQuantity).to.be.not.eq(previousQuantity)
    expect(afterAmount).to.be.not.eq(previousAmount)
    invoice.goInvoicePage()
    invoice.viewInvoice(0)
    invoice.deleteInvoice()
  })
  it('TC-18 Edit the Previously Created Invoice which have some Missing some Information and save it ',()=>{
    invoice.goInvoicePage()
    invoice.viewInvoice(0)
    invoice.editInvoice()
    invoice.addSalesChannel()
    invoice.addDeliveryMethod()
    invoice.addDelivertDetails()
    invoice.clickSaveChanges()

  })
  it('TC-19 ',()=>{
    invoice.goInvoicePage()
    invoice.viewInvoice(0)
    invoice.editInvoice()
    invoice.setQuantity(0,'-3')
    invoice.setPrice(0,'-100')
    invoice.clickSaveChanges()
    invoice.verifyError()
    invoice.setQuantity(0,'1')
    invoice.setPrice(0,'100')
    invoice.clickSaveChanges()
    invoice.verifySuccess()
    
  })
  it('TC-20 Edit the Previously Created Invoice and Validate enter Invalid  Tax Rate with Account',()=>{
    invoice.goInvoicePage()
    invoice.viewInvoice(0)
    invoice.editInvoice()
    invoice.setAccount(0, '15% GST on Expenses')
    invoice.setTax(0, 'No GST ')
    invoice.clickSaveChanges()
    invoice.verifyError()

  })
  it('TC-21 Edit the Previously created Invoice and Verify line Item with one field present (like Quantity)',()=>{
    invoice.goInvoicePage()
    invoice.viewInvoice(0)
    invoice.editInvoice()
    invoice.addRow('addPartsByTagNumber')
    invoice.enterTagNumber()
    invoice.verifySuccess()
  })
  it('TC-22 Edit the Previously created Invoice and Verify the line Item with only the description present',()=>{
    invoice.goInvoicePage()
    invoice.viewInvoice(0)
    invoice.editInvoice()
    invoice.removeAttributesfromROw()
    invoice.clickSaveChanges()
    invoice.verifyError()
  })
  it('TC-23 Edit the Previously created Invoice and Delete Line Items ',()=>{
    invoice.createInvoice()
    invoice.addInvoiceDetails()
    invoice.addRow('addLabour')
    invoice.setDescription(0, 'Car parts')
    invoice.setQuantity(0, '1')
    invoice.setPrice(0, '100')
    invoice.setAccount(0, 'Zero Rated')
    invoice.setTax(0, 'Zero Rated')
    invoice.addRow('addShipping')
    invoice.setDescription(1, 'Shipping')
    invoice.setQuantity(1, '1')
    invoice.setPrice(1, '100')
    invoice.setAccount(1, 'ACCRECPAY')
    invoice.saveCloseButton()
    invoice.verifySuccess()
    invoice.goInvoicePage()
    invoice.viewInvoice(0)
    invoice.editInvoice()
    invoice.deleteRow(0)
    invoice.clickSaveChanges()
    invoice.verifySuccess()
    invoice.deleteInvoice()
  })
  it('TC-24 Edit the Previously created Invoice and Cancel Changes  Invoice',()=>{
    invoice.goInvoicePage()
    invoice.viewInvoice(0)
    invoice.editInvoice()
    invoice.cancelChangesButton()

  })
  it('TC-25 Edit the Previously created Invoice and Preview Edit Invoice',()=>{
    invoice.goInvoicePage()
    invoice.viewInvoice(0)
    invoice.editInvoice()
    invoice.previewInvoice()

  })
  it('TC-26 Preview Invoice and verify some field like contact, quantity and price ',()=>{
    invoice.createInvoice()
    invoice.addInvoiceDetails()
    invoice.addRow('addShipping')
    invoice.setDescription(0,'Shipping')
    invoice.setQuantity(0,'2')
    invoice.setPrice(0,'100')
    invoice.setAccount(0,'Zero Rated')
    invoice.setTax(0,'Zero Rated')
    const previousContact = invoice.getContact()
    const previousPrice = invoice.getPrice()
    const previousQuantity = invoice.getQuantity()
    const previousAmount = invoice.getAmount()
    invoice.saveCloseButton()
    cy.wait(3000)
    invoice.verifySuccess()
    invoice.previewInvoice()
  })
  it('TC-27 Email Invoice With XERO',()=>{
    invoice.createInvoice()
    invoice.addInvoiceDetails()
    invoice.addRow('addShipping')
    invoice.setDescription(0,'Shipping')
    invoice.setQuantity(0,'2')
    invoice.setPrice(0,'100')
    invoice.setAccount(0,'Zero Rated')
    invoice.setTax(0,'Zero Rated')
    invoice.saveCloseButton()
    invoice.verifySuccess()
    cy.wait(3000)
    invoice.approvedButton()
    cy.wait(3000)
    invoice.verifySuccess()
    cy.wait(3000)
    invoice.emailButton()
    cy.wait(3000)
    invoice.verifySuccess()
    cy.reload()
    invoice.validateEmailedTag('Emailed')
  })
  it('TC-28 Approved and Print Invoice With XERO',()=>{
    invoice.createInvoice()
    invoice.addInvoiceDetails()
    invoice.addRow('addShipping')
    invoice.setDescription(0,'Shipping')
    invoice.setQuantity(0,'2')
    invoice.setPrice(0,'100')
    invoice.setAccount(0,'Zero Rated')
    invoice.setTax(0,'Zero Rated')
    invoice.saveCloseButton()
    invoice.verifySuccess()
    cy.wait(3000)
    invoice.printInvoice()
    invoice.deleteInvoice()
  })
  xit('TC-29 Email Invoice Without XERO ',()=>{

  })
  xit('TC-30 Print Invoice Without XERO ',()=>{

  })
  it('TC-31 Approved Invoice ',()=>{
    invoice.createInvoice()
    invoice.addInvoiceDetails()
    invoice.addRow('addShipping')
    invoice.setDescription(0,'Shipping')
    invoice.setQuantity(0,'2')
    invoice.setPrice(0,'100')
    invoice.setAccount(0,'Zero Rated')
    invoice.setTax(0,'Zero Rated')
    invoice.saveCloseButton()
    invoice.verifySuccess()
    cy.wait(3000)
    invoice.approvedButton()
    invoice.verifySuccess()
  })
  it('TC-32 Print Without Part Prices',()=>{
    invoice.goInvoicePage()
    invoice.viewInvoice(0)
    invoice.printWithoutPartPricesButton()
  })
  it('TC-33  Add A Full Payment To An Invoice',()=>{
    invoice.createInvoice()
    invoice.addInvoiceDetails()
    invoice.addRow('addLabour')
    invoice.setDescription(0, 'Car parts')
    invoice.setQuantity(0, '1')
    invoice.setPrice(0, '100')
    invoice.setAccount(0, 'Zero Rated')
    invoice.setTax(0, 'Zero Rated')
    invoice.saveCloseButton()
    invoice.verifySuccess()
    cy.wait(3000)
    invoice.approvedButton()
    invoice.verifySuccess()
    cy.wait(3000)
    invoice.getDueAmount().then(totalstring => {
      cy.log('Total amount is ', totalstring);
    invoice.selectAddPayment()
    invoice.addPaymentDetails(Number(totalstring),Number(totalstring))
    invoice.addPaymentButton()
    invoice.verifySuccess()
    });

  })
  it('TC-34 Add A Partial Payment on the Invoice',()=>{
    invoice.createInvoice()
    invoice.addInvoiceDetails()
    invoice.addRow('addLabour')
    invoice.setDescription(0, 'Car parts')
    invoice.setQuantity(0, '1')
    invoice.setPrice(0, '100')
    invoice.setAccount(0, 'Zero Rated')
    invoice.setTax(0, 'Zero Rated')
    invoice.saveCloseButton()
    invoice.verifySuccess()
    cy.wait(3000)
    invoice.approvedButton()
    invoice.verifySuccess()
    cy.wait(3000)
    invoice.getDueAmount().then(totalstring => {
      cy.log('Total amount is ', totalstring);
      invoice.selectAddPayment()
    invoice.addPaymentDetails(Number(totalstring),50)
    invoice.addPaymentButton()
    invoice.verifySuccess()
    });

  })
  it('TC-35 Print Packing Slip',()=>{
    invoice.goInvoicePage()
    invoice.viewInvoice(0)
    invoice.printPackingInvoice()
  })
  it('TC-36 Dispatch invoice ',()=>{
    invoice.createInvoice()
    invoice.addInvoiceDetails()
    invoice.addRow('addLabour')
    invoice.setDescription(0, 'Car parts')
    invoice.setQuantity(0, '1')
    invoice.setPrice(0, '100')
    invoice.setAccount(0, 'Zero Rated')
    invoice.setTax(0, 'Zero Rated')
    invoice.saveCloseButton()
    invoice.verifySuccess()
    cy.wait(3000)
    invoice.approvedButton()
    invoice.verifySuccess()
    cy.wait(3000)
    invoice.dispatch()
   invoice.verifySuccess()
  })
  it('TC-37 Not Dispatch',()=>{
    invoice.createInvoice()
    invoice.addInvoiceDetails()
    invoice.addRow('addLabour')
    invoice.setDescription(0, 'Car parts')
    invoice.setQuantity(0, '1')
    invoice.setPrice(0, '100')
    invoice.setAccount(0, 'Zero Rated')
    invoice.setTax(0, 'Zero Rated')
    invoice.saveCloseButton()
    invoice.verifySuccess()
    cy.wait(3000)
    invoice.approvedButton()
    invoice.verifySuccess()
    cy.wait(3000)
    invoice.dispatch()
    invoice.verifySuccess()
    cy.wait(3000)
    invoice.notDispatch()
    invoice.verifySuccess()
  })
  it('TC-38  Void Invoice',()=>{
    invoice.createInvoice()
    invoice.addInvoiceDetails()
    invoice.addRow('addLabour')
    invoice.setDescription(0, 'Car parts')
    invoice.setQuantity(0, '1')
    invoice.setPrice(0, '100')
    invoice.setAccount(0, 'Zero Rated')
    invoice.setTax(0, 'Zero Rated')
    invoice.saveCloseButton()
    invoice.verifySuccess()
    cy.wait(3000)
    invoice.approvedButton()
    invoice.verifySuccess()
    cy.wait(3000)
    invoice.void()
    invoice.verifySuccess()
  })
})